theme: jekyll-theme-minimal
plugins:
- jekyll-remote-theme 

title: [CPS 491 Team 3 IlluminationWorks Theia]
description: [Illumination Works Theia AKG for Autonomous Metadata Generation and Linkage User Interface and Service Layer Integration]
