remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme 

title: [CPS 491 Team 3 IlluminationWorks Theia]
description: [Illumination Works Theia AKG for Autonomous Metadata Generation and Linkage User Interface and Service Layer Integration]
