title: CPS 491 Team 3 - Illumination Works
description: Illumination Works Theia AKG for Autonomous Metadata Generation and Linkage User Interface and Service Layer Integration
google_analytics:
theme: jekyll-theme-cayman